name: Lint Unit

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-unit:
    name: Lint checkers and Unit tests
    uses: rgildein/bootstack-github-actions/.github/workflows/lint_unit.yaml@165f83070bf70aaff2764bc762f3aa332b644c0a
    with:
      python-version: '["3.8","3.10"]'
