name: Lint Unit

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  lint-unit:
    name: Lint checkers and Unit tests
    uses: rgildein/bootstack-github-actions/workflows/lint_unit.yaml@workflows/lint-unit-testing
    with:
      python-version: '["3.8", "3.10"]'
